In [1]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
df_raw = pd.read_csv('project2.csv')

In [3]:
df = df_raw.copy(deep= True)

In [4]:
df.head()

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
0,1.0,Fri,2018-08-17,20:15,Girona,0.7,0–0,0.0,Valladolid,10368.0,Estadi Municipal de Montilivi,Guillermo Cuadra
1,1.0,Fri,2018-08-17,22:15,Betis,0.9,0–3,2.5,Levante,46225.0,Estadio Benito Villamarín,Ignacio Iglesias
2,1.0,Sat,2018-08-18,18:15,Celta Vigo,0.6,1–1,0.6,Espanyol,16215.0,Estadio de Balaídos,Santiago Jaime
3,1.0,Sat,2018-08-18,20:15,Villarreal,1.6,1–2,0.7,Real Sociedad,16250.0,Estadio de la Cerámica,Mario Melero
4,1.0,Sat,2018-08-18,22:15,Barcelona,3.2,3–0,0.3,Alavés,52356.0,Camp Nou,José Sánchez

In [5]:
df.count()

Wk            4560
Day           4560
Date          4560
Time          4520
Home          4560
xG            4433
Score         4433
xG.1          4433
Away          4560
Attendance    3502
Venue         4560
Referee       4433
dtype: int64

In [6]:
df.shape

(4560, 12)

In [7]:
df[df.isnull().any(axis= 1)]

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
1029,24.0,Tue,2020-03-10,20:00,Eibar,2.0,1–2,1.2,Real Sociedad,NaN,Estadio Municipal de Ipurúa,David Medié
1030,28.0,Thu,2020-06-11,22:00,Sevilla,1.7,2–0,0.5,Betis,NaN,Estadio Ramón Sánchez Pizjuán,Antonio Matéu Lahoz
1031,28.0,Fri,2020-06-12,19:30,Granada,2.3,2–1,0.6,Getafe,NaN,Estadio Nuevo Los Cármenes,David Medié
1032,28.0,Fri,2020-06-12,22:00,Valencia,1.0,1–1,1.4,Levante,NaN,Estadio de Mestalla,Alberola Rojas
1033,28.0,Sat,2020-06-13,14:00,Espanyol,2.5,2–0,0.1,Alavés,NaN,RCDE Stadium,Pablo González
...,...,...,...,...,...,...,...,...,...,...,...,...
4555,38.0,Sun,2024-05-19,16:00,Brentford,NaN,NaN,NaN,Newcastle Utd,NaN,Gtech Community Stadium,NaN
4556,38.0,Sun,2024-05-19,16:00,Chelsea,NaN,NaN,NaN,Bournemouth,NaN,Stamford Bridge,NaN
4557,38.0,Sun,2024-05-19,16:00,Crystal Palace,NaN,NaN,NaN,Aston Villa,NaN,Selhurst Park,NaN
4558,38.0,Sun,2024-05-19,16:00,Liverpool,NaN,NaN,NaN,Wolves,NaN,Anfield,NaN
4559,38.0,Sun,2024-05-19,16:00,Burnley,NaN,NaN,NaN,Nott'ham Forest,NaN,Turf Moor,NaN

In [8]:
df = df.dropna(subset= ['Score'])

df.shape

(4433, 12)

In [9]:
df = df.drop(columns= ['Attendance', 'Time'])

In [10]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee
0,1.0,Fri,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra
1,1.0,Fri,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias
2,1.0,Sat,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime
3,1.0,Sat,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero
4,1.0,Sat,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez

In [11]:
df[['home_goals', 'away_goals']] = df['Score'].str.split('–', expand= True).astype(int)

In [12]:
df.head(
    
)

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals
0,1.0,Fri,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0
1,1.0,Fri,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3
2,1.0,Sat,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1
3,1.0,Sat,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2
4,1.0,Sat,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0

In [13]:
def det_res(row):
    if row['home_goals'] > row['away_goals']:
        return 'Home win'
    
    elif row['home_goals'] < row['away_goals']:
        return 'Away win'

    else:
        return 'Draw'

In [14]:
df['result'] = df.apply(det_res, axis= 1)

In [15]:
df['result']

0           Draw
1       Away win
2           Draw
3       Away win
4       Home win
          ...
4498        Draw
4499    Away win
4500    Away win
4501    Away win
4502    Home win
Name: result, Length: 4433, dtype: str

In [16]:
df['Date'] = pd.to_datetime(df['Date'])

df['Day'] = df['Date'].dt.day_name()

In [17]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals,result
0,1.0,Friday,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0,Draw
1,1.0,Friday,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3,Away win
2,1.0,Saturday,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1,Draw
3,1.0,Saturday,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2,Away win
4,1.0,Saturday,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0,Home win

In [18]:
df['season_start'] = df['Date'].apply(lambda x : x.year == 1 if x.month < 8 else x.year)

In [19]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals,result,season_start
0,1.0,Friday,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0,Draw,2018
1,1.0,Friday,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3,Away win,2018
2,1.0,Saturday,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1,Draw,2018
3,1.0,Saturday,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2,Away win,2018
4,1.0,Saturday,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0,Home win,2018

In [20]:
df = pd.get_dummies(df, columns= ['Day'])

In [21]:
df.head()

,Wk,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals,result,season_start,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,1.0,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0,Draw,2018,True,False,False,False,False,False,False
1,1.0,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3,Away win,2018,True,False,False,False,False,False,False
2,1.0,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1,Draw,2018,False,False,True,False,False,False,False
3,1.0,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2,Away win,2018,False,False,True,False,False,False,False
4,1.0,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0,Home win,2018,False,False,True,False,False,False,False

In [22]:
df.reset_index(drop = True, inplace= True)

In [23]:
for x in df.Home.unique():
    
    temp_df = df[(df['Home'] == x) | (df['Away'] == x)]

    temp_df = temp_df.sort_values(['Date'])

    temp_df['goal_value_to_calc'] = temp_df.apply(lambda y : y['home_goals'] if y['Home'] == x else y['away_goals'], axis= 1)
    
    temp_df['rolling_avg_goals'] = temp_df['goal_value_to_calc'].rolling(window= 5, closed= 'left', min_periods= 1).mean()

    for index, row in temp_df.iterrows():
        if row['Home'] == x:
            df['home_rolling_avg_goals'] = pd.NA
            df['away_rolling_avg_goals'] = pd.NA

            for x in df.Home.unique():
                temp_df = df[(df['Home'] == x) | (df['Away'] == x)]
                temp_df = temp_df.sort_values(['Date'])

                temp_df['goal_value_to_calc'] = temp_df.apply(
                    lambda y: y['home_goals'] if y['Home'] == x else y['away_goals'],
                    axis=1
                )
                temp_df['rolling_avg_goals'] = temp_df['goal_value_to_calc'].rolling(
                    window=5, closed='left', min_periods=1
                ).mean()

                for index, row in temp_df.iterrows():
                    if row['Home'] == x:
                        df.at[index, 'home_rolling_avg_goals'] = row['rolling_avg_goals']
                    else:
                        df.at[index, 'away_rolling_avg_goals'] = row['rolling_avg_goals']

        else:
            df.at[index, 'away_rolling_avg_goals'] == row['rolling_avg_goals']

In [24]:
temp_df.head()

,Wk,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,...,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday,home_rolling_avg_goals,away_rolling_avg_goals,goal_value_to_calc,rolling_avg_goals
4114,1.0,2023-08-12,Brighton,4.0,4–1,1.5,Luton Town,The American Express Community Stadium,David Coote,4,...,False,True,False,False,False,False,1.8,<NA>,1,NaN
4129,3.0,2023-08-25,Chelsea,2.2,3–0,0.4,Luton Town,Stamford Bridge,Robert Jones,3,...,False,False,False,False,False,False,0.8,<NA>,0,1.000000
4139,4.0,2023-09-01,Luton Town,1.4,1–2,1.0,West Ham,Kenilworth Road Stadium,Paul Tierney,1,...,False,False,False,False,False,False,<NA>,2.2,1,0.500000
4150,5.0,2023-09-16,Fulham,1.0,1–0,1.1,Luton Town,Craven Cottage,Michael Salisbury,1,...,False,True,False,False,False,False,1.0,<NA>,0,0.666667
4160,6.0,2023-09-23,Luton Town,2.1,1–1,0.6,Wolves,Kenilworth Road Stadium,Joshua Smith,1,...,False,True,False,False,False,False,<NA>,1.0,1,0.500000

In [25]:
df.columns

Index(['Wk', 'Date', 'Home', 'xG', 'Score', 'xG.1', 'Away', 'Venue', 'Referee',
       'home_goals', 'away_goals', 'result', 'season_start', 'Day_Friday',
       'Day_Monday', 'Day_Saturday', 'Day_Sunday', 'Day_Thursday',
       'Day_Tuesday', 'Day_Wednesday', 'home_rolling_avg_goals',
       'away_rolling_avg_goals'],
      dtype='str')

In [26]:
for x in df.Home.unique():
    
    temp_df = df[(df['Home'] == x) | (df['Away'] == x)]

    temp_df = temp_df.sort_values(['Date'])

    temp_df['xG_value_to_calc'] = temp_df.apply(lambda y : y['xG'] if y['Home'] == x else y['xG.1'], axis= 1)
    
    temp_df['rolling_avg_xG'] = temp_df['xG_value_to_calc'].rolling(window= 5, closed= 'left', min_periods= 1).mean()

    for index, row in temp_df.iterrows():
        if row['Home'] == x:
            df['home_rolling_avg_xG'] = pd.NA
            df['away_rolling_avg_xG'] = pd.NA

            for x in df.Home.unique():
                temp_df = df[(df['Home'] == x) | (df['Away'] == x)]
                temp_df = temp_df.sort_values(['Date'])

                temp_df['xG_value_to_calc'] = temp_df.apply(
                    lambda y: y['xG'] if y['Home'] == x else y['xG.1'],
                    axis=1
                )
                temp_df['rolling_avg_xG'] = temp_df['xG_value_to_calc'].rolling(
                    window=5, closed='left', min_periods=1
                ).mean()

                for index, row in temp_df.iterrows():
                    if row['Home'] == x:
                        df.at[index, 'home_rolling_avg_xG'] = row['rolling_avg_xG']
                    else:
                        df.at[index, 'away_rolling_avg_xG'] = row['rolling_avg_xG']

        else:
            df.at[index, 'away_rolling_avg_xG'] == row['rolling_avg_xG']

In [27]:
df.columns

Index(['Wk', 'Date', 'Home', 'xG', 'Score', 'xG.1', 'Away', 'Venue', 'Referee',
       'home_goals', 'away_goals', 'result', 'season_start', 'Day_Friday',
       'Day_Monday', 'Day_Saturday', 'Day_Sunday', 'Day_Thursday',
       'Day_Tuesday', 'Day_Wednesday', 'home_rolling_avg_goals',
       'away_rolling_avg_goals', 'home_rolling_avg_xG', 'away_rolling_avg_xG'],
      dtype='str')

In [28]:
df = df.dropna(subset= ['home_rolling_avg_goals',
       'away_rolling_avg_goals', 'home_rolling_avg_xG', 'away_rolling_avg_xG'])

In [29]:
df[(df['Home'] == 'Manchester City') | (df['Away'] == 'Manchester City')]

,Wk,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,...,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday,home_rolling_avg_goals,away_rolling_avg_goals,home_rolling_avg_xG,away_rolling_avg_xG
397,2.0,2018-08-19,Manchester City,4.2,6–1,0.7,Huddersfield,Etihad Stadium,Andre Marriner,6,...,False,False,True,False,False,False,2.0,0.0,1.7,0.3
400,3.0,2018-08-25,Wolves,1.0,1–1,1.6,Manchester City,Molineux Stadium,Martin Atkinson,1,...,False,True,False,False,False,False,1.0,4.0,1.05,2.95
416,4.0,2018-09-01,Manchester City,2.0,2–1,0.5,Newcastle Utd,Etihad Stadium,Kevin Friend,2,...,False,True,False,False,False,False,3.0,0.666667,2.5,0.933333
421,5.0,2018-09-15,Manchester City,4.8,3–0,0.4,Fulham,Etihad Stadium,Stuart Attwell,3,...,False,True,False,False,False,False,2.75,1.75,2.375,1.3
432,6.0,2018-09-22,Cardiff City,0.1,0–5,2.5,Manchester City,Cardiff City Stadium,Michael Oliver,0,...,False,True,False,False,False,False,0.6,2.8,0.98,2.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4386,28.0,2024-03-10,Liverpool,2.7,1–1,1.6,Manchester City,Anfield,Michael Oliver,1,...,False,False,True,False,False,False,2.6,1.6,2.26,2.28
4402,30.0,2024-03-31,Manchester City,1.0,0–0,0.7,Arsenal,Etihad Stadium,Anthony Taylor,0,...,False,False,True,False,False,False,1.4,4.6,2.28,2.46
4410,31.0,2024-04-03,Manchester City,3.4,4–1,0.8,Aston Villa,Etihad Stadium,Darren England,4,...,False,False,False,False,False,True,1.2,2.0,1.96,1.6
4413,32.0,2024-04-06,Crystal Palace,1.1,2–4,1.9,Manchester City,Selhurst Park,Paul Tierney,2,...,False,True,False,False,False,False,1.2,1.8,1.36,2.18
4424,33.0,2024-04-13,Manchester City,4.2,5–1,0.5,Luton Town,Etihad Stadium,John Brooks,5,...,False,True,False,False,False,False,2.4,1.4,2.24,0.98

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [31]:
df.columns

Index(['Wk', 'Date', 'Home', 'xG', 'Score', 'xG.1', 'Away', 'Venue', 'Referee',
       'home_goals', 'away_goals', 'result', 'season_start', 'Day_Friday',
       'Day_Monday', 'Day_Saturday', 'Day_Sunday', 'Day_Thursday',
       'Day_Tuesday', 'Day_Wednesday', 'home_rolling_avg_goals',
       'away_rolling_avg_goals', 'home_rolling_avg_xG', 'away_rolling_avg_xG'],
      dtype='str')

In [32]:
features = [cols for cols in df.drop(columns= ['Date', 'xG', 'xG.1', 'Home', 'Away', 'Referee', 'Venue', 'Score', 'result', 'home_goals', 'away_goals', 'season_start'])]

In [33]:
features

['Wk',
 'Day_Friday',
 'Day_Monday',
 'Day_Saturday',
 'Day_Sunday',
 'Day_Thursday',
 'Day_Tuesday',
 'Day_Wednesday',
 'home_rolling_avg_goals',
 'away_rolling_avg_goals',
 'home_rolling_avg_xG',
 'away_rolling_avg_xG']

In [34]:
train_df = df[df['season_start'] <= 2022]
test_df  = df[df['season_start'] == 2023]

x_train = train_df[features]
y_train = train_df['result']

x_test = test_df[features]
y_test = test_df['result']

In [35]:
train_df.shape

(4024, 24)

In [36]:
x_train.shape

(4024, 12)

In [37]:
x_test.shape

(374, 12)

In [38]:
clf = RandomForestClassifier(random_state= 42)

clf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [39]:
pred = clf.predict(x_test)

In [40]:
accuracy_score(y_test, pred)

0.4358288770053476

In [41]:
df['result'].value_counts(normalize= True)

result
Home win    0.445884
Away win    0.303547
Draw        0.250568
Name: proportion, dtype: float64

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
param_grid = {
    'n_estimators' : [50, 100, 200],
    'max_depth' : [5, 10, 15, 20],
}

gs = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 5)

In [44]:
gs.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [5, 10, 15, 20],
                         'n_estimators': [50, 100, 200]})

In [45]:
gs.best_params_

{'max_depth': 5, 'n_estimators': 50}

In [46]:
clf_new = RandomForestClassifier(random_state= 42, max_depth= 5, n_estimators= 50)

clf_new.fit(x_train, y_train)

pred2 = clf_new.predict(x_test)

accuracy_score(y_test, pred2)

0.48663101604278075

In [47]:
df = pd.get_dummies(df, columns= ['Home', 'Away', 'Referee', 'Venue'])

df.head()

,Wk,Date,xG,Score,xG.1,home_goals,away_goals,result,season_start,Day_Friday,...,Venue_The American Express Community Stadium,Venue_The City Ground,Venue_The Hawthorns,Venue_The John Smith's Stadium,Venue_Tottenham Hotspur Stadium,Venue_Turf Moor,Venue_Vicarage Road Stadium,Venue_Villa Park,Venue_Vitality Stadium,Venue_Wembley Stadium
10,2.0,2018-08-24,1.4,2–0,0.6,2,0,Home win,2018,True,...,False,False,False,False,False,False,False,False,False,False
11,2.0,2018-08-24,1.7,2–2,1.6,2,2,Draw,2018,True,...,False,False,False,False,False,False,False,False,False,False
12,2.0,2018-08-25,0.6,0–0,0.9,0,0,Draw,2018,False,...,False,False,False,False,False,False,False,False,False,False
13,2.0,2018-08-25,0.9,1–0,1.5,1,0,Home win,2018,False,...,False,False,False,False,False,False,False,False,False,False
14,2.0,2018-08-25,0.4,0–1,1.0,0,1,Away win,2018,False,...,False,False,False,False,False,False,False,False,False,False

In [48]:
features = [cols for cols in df.drop(columns= ['Date', 'xG', 'xG.1', 'Score', 'result', 'home_goals', 'away_goals', 'season_start'])]

In [49]:
train_df = df[df['season_start'] <= 2022]
test_df  = df[df['season_start'] == 2023]

x_train = train_df[features]
y_train = train_df['result']

x_test = test_df[features]
y_test = test_df['result']

In [50]:
param_grid = {
    'n_estimators' : [50, 100, 200],
    'max_depth' : [5, 10, 15, 20],
}

gs = GridSearchCV(estimator=clf, param_grid=param_grid, cv = 5)

gs.fit(x_train, y_train)

gs.best_params_

{'max_depth': 20, 'n_estimators': 200}

In [52]:
clf = RandomForestClassifier(random_state= 42, max_depth= 20, n_estimators= 200)

clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test, y_pred)

0.5187165775401069

In [53]:
home_team = 'Chealse'
away_team = 'Manchester City'
referee = 'Anthony Taylor'

In [54]:
# Essentially, we need to create a row of data that represents the match we want to predict
# We'll use the features we used to train the model

# Create a row of data for the hypothetical match
data = {
    'Wk': [25],
    'home_rolling_avg_goals': [1.9],
    'away_rolling_avg_goals': [1.2],
    'home_rolling_avg_xG': [2.1],
    'away_rolling_avg_xG': [1.3],
    'Day_Saturday': [1],
    'Home_Chelsea': [1],
    'Away_Manchester Utd': [1],
    'Referee_Anthony Taylor': [1],
    'Venue_Stamford Bridge': [1]
}

match = pd.DataFrame(columns=x_train.columns, data=data)

match.fillna(0, inplace=True)

,Wk,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday,home_rolling_avg_goals,away_rolling_avg_goals,...,Venue_The American Express Community Stadium,Venue_The City Ground,Venue_The Hawthorns,Venue_The John Smith's Stadium,Venue_Tottenham Hotspur Stadium,Venue_Turf Moor,Venue_Vicarage Road Stadium,Venue_Villa Park,Venue_Vitality Stadium,Venue_Wembley Stadium
0,25,0,0,1,0,0,0,0,1.9,1.2,...,0,0,0,0,0,0,0,0,0,0

In [55]:
# Use the Random Forest model to predict the outcome of the match
prediction = clf.predict(match)
prediction

array(['Home win'], dtype=object)