In [1]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
df_raw = pd.read_csv('project2.csv')

In [3]:
df = df_raw.copy(deep= True)

In [4]:
df.head()

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
0,1.0,Fri,2018-08-17,20:15,Girona,0.7,0–0,0.0,Valladolid,10368.0,Estadi Municipal de Montilivi,Guillermo Cuadra
1,1.0,Fri,2018-08-17,22:15,Betis,0.9,0–3,2.5,Levante,46225.0,Estadio Benito Villamarín,Ignacio Iglesias
2,1.0,Sat,2018-08-18,18:15,Celta Vigo,0.6,1–1,0.6,Espanyol,16215.0,Estadio de Balaídos,Santiago Jaime
3,1.0,Sat,2018-08-18,20:15,Villarreal,1.6,1–2,0.7,Real Sociedad,16250.0,Estadio de la Cerámica,Mario Melero
4,1.0,Sat,2018-08-18,22:15,Barcelona,3.2,3–0,0.3,Alavés,52356.0,Camp Nou,José Sánchez

In [5]:
df.count()

Wk            4560
Day           4560
Date          4560
Time          4520
Home          4560
xG            4433
Score         4433
xG.1          4433
Away          4560
Attendance    3502
Venue         4560
Referee       4433
dtype: int64

In [6]:
df.shape

(4560, 12)

In [7]:
df[df.isnull().any(axis= 1)]

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee
1029,24.0,Tue,2020-03-10,20:00,Eibar,2.0,1–2,1.2,Real Sociedad,NaN,Estadio Municipal de Ipurúa,David Medié
1030,28.0,Thu,2020-06-11,22:00,Sevilla,1.7,2–0,0.5,Betis,NaN,Estadio Ramón Sánchez Pizjuán,Antonio Matéu Lahoz
1031,28.0,Fri,2020-06-12,19:30,Granada,2.3,2–1,0.6,Getafe,NaN,Estadio Nuevo Los Cármenes,David Medié
1032,28.0,Fri,2020-06-12,22:00,Valencia,1.0,1–1,1.4,Levante,NaN,Estadio de Mestalla,Alberola Rojas
1033,28.0,Sat,2020-06-13,14:00,Espanyol,2.5,2–0,0.1,Alavés,NaN,RCDE Stadium,Pablo González
...,...,...,...,...,...,...,...,...,...,...,...,...
4555,38.0,Sun,2024-05-19,16:00,Brentford,NaN,NaN,NaN,Newcastle Utd,NaN,Gtech Community Stadium,NaN
4556,38.0,Sun,2024-05-19,16:00,Chelsea,NaN,NaN,NaN,Bournemouth,NaN,Stamford Bridge,NaN
4557,38.0,Sun,2024-05-19,16:00,Crystal Palace,NaN,NaN,NaN,Aston Villa,NaN,Selhurst Park,NaN
4558,38.0,Sun,2024-05-19,16:00,Liverpool,NaN,NaN,NaN,Wolves,NaN,Anfield,NaN
4559,38.0,Sun,2024-05-19,16:00,Burnley,NaN,NaN,NaN,Nott'ham Forest,NaN,Turf Moor,NaN

In [9]:
df = df.dropna(subset= ['Score'])

df.shape

(4433, 12)

In [10]:
df = df.drop(columns= ['Attendance', 'Time'])

In [11]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee
0,1.0,Fri,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra
1,1.0,Fri,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias
2,1.0,Sat,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime
3,1.0,Sat,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero
4,1.0,Sat,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez

In [12]:
df[['home_goals', 'away_goals']] = df['Score'].str.split('–', expand= True).astype(int)

In [13]:
df.head(
    
)

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals
0,1.0,Fri,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0
1,1.0,Fri,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3
2,1.0,Sat,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1
3,1.0,Sat,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2
4,1.0,Sat,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0

In [14]:
def det_res(row):
    if row['home_goals'] > row['away_goals']:
        return 'Home win'
    
    elif row['home_goals'] < row['away_goals']:
        return 'Away win'

    else:
        return 'Draw'

In [15]:
df['result'] = df.apply(det_res, axis= 1)

In [16]:
df['result']

0           Draw
1       Away win
2           Draw
3       Away win
4       Home win
          ...
4498        Draw
4499    Away win
4500    Away win
4501    Away win
4502    Home win
Name: result, Length: 4433, dtype: str

In [17]:
df['Date'] = pd.to_datetime(df['Date'])

df['Day'] = df['Date'].dt.day_name()

In [18]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals,result
0,1.0,Friday,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0,Draw
1,1.0,Friday,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3,Away win
2,1.0,Saturday,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1,Draw
3,1.0,Saturday,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2,Away win
4,1.0,Saturday,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0,Home win

In [20]:
df['season_start'] = df['Date'].apply(lambda x : x.year == 1 if x.month < 8 else x.year)

In [21]:
df.head()

,Wk,Day,Date,Home,xG,Score,xG.1,Away,Venue,Referee,home_goals,away_goals,result,season_start
0,1.0,Friday,2018-08-17,Girona,0.7,0–0,0.0,Valladolid,Estadi Municipal de Montilivi,Guillermo Cuadra,0,0,Draw,2018
1,1.0,Friday,2018-08-17,Betis,0.9,0–3,2.5,Levante,Estadio Benito Villamarín,Ignacio Iglesias,0,3,Away win,2018
2,1.0,Saturday,2018-08-18,Celta Vigo,0.6,1–1,0.6,Espanyol,Estadio de Balaídos,Santiago Jaime,1,1,Draw,2018
3,1.0,Saturday,2018-08-18,Villarreal,1.6,1–2,0.7,Real Sociedad,Estadio de la Cerámica,Mario Melero,1,2,Away win,2018
4,1.0,Saturday,2018-08-18,Barcelona,3.2,3–0,0.3,Alavés,Camp Nou,José Sánchez,3,0,Home win,2018