In [11]:

id = 'stats_standard'
url = 'https://fbref.com/en/comps/Big5/2022-2023/2022-2023-Big-5-European-Leagues-Stats'

In [17]:
import pandas as pd

from tabulate import tabulate


import undetected_chromedriver as uc
from bs4 import BeautifulSoup
driver = uc.Chrome(version_main=148)

In [18]:
driver.get(url)

In [27]:
df_raw = pd.read_html(driver.page_source, attrs= {'id' : 'big5_table'})[0]

df_raw.head()

C:\Users\pawan\AppData\Local\Temp\ipykernel_25884\3353009956.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_raw = pd.read_html(driver.page_source, attrs= {'id' : 'big5_table'})[0]

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
0,1,Napoli,it ITA,1,38,28,6,4,77,28,+49,90,2.37,46173,Victor Osimhen - 26,Alex Meret
1,2,Manchester City,eng ENG,1,38,28,5,5,94,33,+61,89,2.34,53249,Erling Haaland - 36,Ederson
2,3,Barcelona,es ESP,1,38,28,4,6,70,20,+50,88,2.32,83498,Robert Lewandowski - 23,Marc-André ter Stegen
3,4,Paris Saint-Germain,fr FRA,1,38,27,4,7,89,40,+49,85,2.24,46334,Kylian Mbappé - 29,Gianluigi Donnarumma
4,5,Arsenal,eng ENG,2,38,26,6,6,88,43,+45,84,2.21,60191,"Martin Ødegaard, Gabriel Martinelli - 15",Aaron Ramsdale

In [29]:
df = df_raw.sort_values('GD')
df

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
44,43,Torino,it ITA,10,38,14,11,13,42,41,+1,53,1.39,19464,Antonio Sanabria - 12,Vanja Milinković-Savić
37,37,Fiorentina,it ITA,8,38,15,11,12,53,43,+10,56,1.47,32200,Arthur Cabral - 8,Pietro Terracciano
36,36,Nice,fr FRA,9,38,15,13,10,48,37,+11,58,1.53,22286,Gaëtan Laborde - 13,Kasper Schmeichel
34,34,Brentford,eng ENG,9,38,15,14,9,58,46,+12,59,1.55,17078,Ivan Toney - 20,David Raya
24,24,Monaco,fr FRA,6,38,19,8,11,70,58,+12,65,1.71,7095,Wissam Ben Yedder - 19,Alexander Nübel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,49,Reims,fr FRA,11,38,12,15,11,45,45,0,51,1.34,13290,Folarin Balogun - 21,Yehvann Diouf
62,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
41,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
20,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
83,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper

In [30]:
df = df.drop_duplicates()

In [31]:
df.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper
44,43,Torino,it ITA,10,38,14,11,13,42,41,+1,53,1.39,19464,Antonio Sanabria - 12,Vanja Milinković-Savić
37,37,Fiorentina,it ITA,8,38,15,11,12,53,43,+10,56,1.47,32200,Arthur Cabral - 8,Pietro Terracciano
36,36,Nice,fr FRA,9,38,15,13,10,48,37,+11,58,1.53,22286,Gaëtan Laborde - 13,Kasper Schmeichel
34,34,Brentford,eng ENG,9,38,15,14,9,58,46,+12,59,1.55,17078,Ivan Toney - 20,David Raya
24,24,Monaco,fr FRA,6,38,19,8,11,70,58,+12,65,1.71,7095,Wissam Ben Yedder - 19,Alexander Nübel