In [2]:
import pandas as pd

import numpy as np

In [3]:
data = pd.DataFrame({
    'name' : ['Messi', 'Ronaldo', 'Neymar', 'Lingard', 'Mbappe', 'Messi'],
    'goals' : [45, 43, 32, 10.34, 39, 10],
    'assists' : [28, 14, 19, np.nan, 7, 20],
    'position' : ['Forward', 'Forward', 'Forward', 'Midfielder', 'FWD', 'FWD'],
    'birth-date' : ['1987-06-24 00:00:00', '1985-02-05', '1992-02-05', '1992-12-20', '1998-12-20', '1987-06-24 00:00:00']
})

In [4]:
data

      name  goals  assists    position           birth-date
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      NaN  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20
5    Messi  10.00     20.0         FWD  1987-06-24 00:00:00

In [5]:
data = pd.concat([data, data])

In [6]:
data

      name  goals  assists    position           birth-date
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      NaN  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20
5    Messi  10.00     20.0         FWD  1987-06-24 00:00:00
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      NaN  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20
5    Messi  10.00     20.0         FWD  1987-06-24 00:00:00

In [7]:
data = data.drop_duplicates()

In [8]:
data

      name  goals  assists    position           birth-date
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      NaN  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20
5    Messi  10.00     20.0         FWD  1987-06-24 00:00:00

In [9]:
data = data.drop_duplicates(subset= ['name'], keep = 'first')
data

      name  goals  assists    position           birth-date
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      NaN  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20

In [10]:
data['assists'] = data['assists'].fillna(0)
data

C:\Users\pawan\AppData\Local\Temp\ipykernel_19516\3025116441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['assists'] = data['assists'].fillna(0)

      name  goals  assists    position           birth-date
0    Messi  45.00     28.0     Forward  1987-06-24 00:00:00
1  Ronaldo  43.00     14.0     Forward           1985-02-05
2   Neymar  32.00     19.0     Forward           1992-02-05
3  Lingard  10.34      0.0  Midfielder           1992-12-20
4   Mbappe  39.00      7.0         FWD           1998-12-20

In [12]:
data[['goals', 'assists']] = data[['goals', 'assists']].astype(int)

C:\Users\pawan\AppData\Local\Temp\ipykernel_19516\3545630470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['goals', 'assists']] = data[['goals', 'assists']].astype(int)

In [13]:
data['position'] = data['position'].str.replace('FWD', 'Forward')
data

C:\Users\pawan\AppData\Local\Temp\ipykernel_19516\3007987745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['position'] = data['position'].str.replace('FWD', 'Forward')

      name  goals  assists    position           birth-date
0    Messi     45       28     Forward  1987-06-24 00:00:00
1  Ronaldo     43       14     Forward           1985-02-05
2   Neymar     32       19     Forward           1992-02-05
3  Lingard     10        0  Midfielder           1992-12-20
4   Mbappe     39        7     Forward           1998-12-20

In [15]:
data['birth-date']  = pd.to_datetime(data['birth-date'], format='mixed')

C:\Users\pawan\AppData\Local\Temp\ipykernel_19516\2965790509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['birth-date']  = pd.to_datetime(data['birth-date'], format='mixed')

In [16]:
data

      name  goals  assists    position birth-date
0    Messi     45       28     Forward 1987-06-24
1  Ronaldo     43       14     Forward 1985-02-05
2   Neymar     32       19     Forward 1992-02-05
3  Lingard     10        0  Midfielder 1992-12-20
4   Mbappe     39        7     Forward 1998-12-20