In [12]:
import pandas as pd
import undetected_chromedriver as uc
from bs4 import BeautifulSoup

In [ ]:
driver = uc.Chrome(version_main=148)

In [14]:
driver.get('https://fbref.com/en/comps/8/2022-2023/stats/2022-2023-Champions-League-Stats#all_stats_squads_standard')

In [19]:
df = pd.read_html(driver.page_source, attrs= {'id': "stats_squads_standard_for"})[0]

C:\Users\pawan\AppData\Local\Temp\ipykernel_29364\2994241610.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(driver.page_source, attrs= {'id': "stats_squads_standard_for"})[0]

In [20]:
df.head()

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0             nl Ajax                 19               26.4
1  es Atlético Madrid                 22               28.6
2        es Barcelona                 26               26.4
3    de Bayern Munich                 24               26.6
4          pt Benfica                 24               26.0

  Unnamed: 3_level_0 Playing Time                   Performance      ...       \
                Poss           MP Starts  Min   90s         Gls Ast  ... G-PK
0               53.2            6     66  540   6.0          11   9  ...   10
1               56.5            6     66  540   6.0           4   3  ...    4
2               64.8            6     66  540   6.0          12  10  ...   12
3               56.1           10    110  900  10.0          21  19  ...   20
4               52.9           10    110  900  10.0          25  16  ...   20

                     Per 90 Minutes
  PK PKatt CrdY CrdR            Gls   Ast   G+A  G-PK G+A-PK
0  1     1   15    1           1.83  1.50  3.33  1.67   3.17
1  0     2   13    0           0.67  0.50  1.17  0.67   1.17
2  0     0   10    0           2.00  1.67  3.67  2.00   3.67
3  1     1   20    1           2.10  1.90  4.00  2.00   3.90
4  5     5   19    0           2.50  1.60  4.10  2.00   3.60

[5 rows x 21 columns]

In [21]:
player_stats = pd.read_html(driver.page_source, attrs= {'id' : "stats_standard"})[0]
player_stats.head()

C:\Users\pawan\AppData\Local\Temp\ipykernel_29364\4148068724.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_stats = pd.read_html(driver.page_source, attrs= {'id' : "stats_standard"})[0]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Liel Abada             il ISR              MF,FW
1                  2  Oliver Abildgaard             dk DEN              DF,MF
2                  3  Mohammad Abu Fani             il ISR                 MF
3                  4   Francesco Acerbi             it ITA                 DF
4                  5       Marcos Acuña             ar ARG              DF,MF

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Playing Time  \
               Squad                Age               Born           MP
0         sct Celtic                 20               2001            5
1         sct Celtic                 26               1996            2
2   il Maccabi Haifa                 24               1998            6
3           it Inter                 34               1988           12
4         es Sevilla                 30               1991            4

               ... Performance                 Per 90 Minutes              \
  Starts  Min  ...          PK PKatt CrdY CrdR            Gls   Ast   G+A
0      4  217  ...           0     0    0    0           0.00  0.00  0.00
1      0   63  ...           0     0    0    0           0.00  0.00  0.00
2      4  400  ...           0     0    1    0           0.00  0.00  0.00
3     10  921  ...           0     0    1    0           0.00  0.00  0.00
4      3  219  ...           0     0    0    0           0.00  0.41  0.41

               Unnamed: 24_level_0
   G-PK G+A-PK             Matches
0  0.00   0.00             Matches
1  0.00   0.00             Matches
2  0.00   0.00             Matches
3  0.00   0.00             Matches
4  0.00   0.41             Matches

[5 rows x 25 columns]

In [24]:
player_stats

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk             Player             Nation
0                    1         Liel Abada             il ISR
1                    2  Oliver Abildgaard             dk DEN
2                    3  Mohammad Abu Fani             il ISR
3                    4   Francesco Acerbi             it ITA
4                    5       Marcos Acuña             ar ARG
..                 ...                ...                ...
751                724    Piotr Zieliński             pl POL
752                725       Hakim Ziyech             ma MAR
753                 Rk             Player             Nation
754                726   Oleksandr Zubkov             ua UKR
755                727      Neven Đurasek             hr CRO

    Unnamed: 3_level_0   Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos                Squad                Age
0                MF,FW           sct Celtic                 20
1                DF,MF           sct Celtic                 26
2                   MF     il Maccabi Haifa                 24
3                   DF             it Inter                 34
4                DF,MF           es Sevilla                 30
..                 ...                  ...                ...
751                 MF            it Napoli                 28
752                 MF          eng Chelsea                 29
753                Pos                Squad                Age
754              MF,FW  ua Shakhtar Donetsk                 25
755                 MF  ua Shakhtar Donetsk                 23

    Unnamed: 6_level_0 Playing Time               ... Performance         \
                  Born           MP  Starts  Min  ...          PK  PKatt
0                 2001            5       4  217  ...           0      0
1                 1996            2       0   63  ...           0      0
2                 1998            6       4  400  ...           0      0
3                 1988           12      10  921  ...           0      0
4                 1991            4       3  219  ...           0      0
..                 ...          ...     ...  ...  ...         ...    ...
751               1994           10       8  619  ...           2      3
752               1993            4       1  148  ...           0      0
753               Born           MP  Starts  Min  ...          PK  PKatt
754               1996            5       5  365  ...           0      0
755               1998            5       0   91  ...           0      0

                Per 90 Minutes                           Unnamed: 24_level_0
     CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
0       0     0           0.00  0.00  0.00  0.00    0.00             Matches
1       0     0           0.00  0.00  0.00  0.00    0.00             Matches
2       1     0           0.00  0.00  0.00  0.00    0.00             Matches
3       1     0           0.00  0.00  0.00  0.00    0.00             Matches
4       0     0           0.00  0.41  0.41  0.00    0.41             Matches
..    ...   ...            ...   ...   ...   ...     ...                 ...
751     1     0           0.58  0.29  0.87  0.29    0.58             Matches
752     1     0           0.00  0.00  0.00  0.00    0.00             Matches
753  CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
754     1     0           0.49  0.00  0.49  0.49    0.49             Matches
755     1     0           0.00  0.00  0.00  0.00    0.00             Matches

[756 rows x 25 columns]